import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import worker from "../src/index.js";
import { LANDING_PAGE_HTML, LANDING_PAGE_SCRIPT } from "../src/landing.js";
import { AI_CRAWLER_USER_AGENTS, buildLlmsTxt, buildRobotsTxt, buildSitemapXml } from "../src/seo.js";
import { listDatasetEntries } from "../src/registry/index.js";
import "../src/registry/cwa.js";
import "../src/registry/moenv.js";
import "../src/registry/tdx.js";
import "../src/registry/highway.js";

const env = {} as never;
const ORIGIN = "https://example.com";

function siteFile(name: string): string {
  return readFileSync(fileURLToPath(new URL(`../site/${name}`, import.meta.url)), "utf-8");
}

describe("landing.ts stays in sync with site/", () => {
  // src/landing.ts is a generated byte-embed of the two files in site/, which
  // are the real source. Nothing but discipline previously stopped the two
  // from drifting — edit site/index.html, forget to regenerate, and the
  // deployed page silently keeps serving the old bytes. These two assertions
  // turn that into a test failure.
  it("embeds site/index.html byte-for-byte", () => {
    expect(LANDING_PAGE_HTML).toBe(siteFile("index.html"));
  });

  it("embeds site/support.js byte-for-byte", () => {
    expect(LANDING_PAGE_SCRIPT).toBe(siteFile("support.js"));
  });
});

describe("landing page SEO/AEO markup", () => {
  const html = siteFile("index.html");

  it("has a title and a description that names what the service actually covers", () => {
    expect(html).toContain("<title>opendata-mcp — 台灣開放資料 MCP 閘道</title>");
    const description = /<meta name="description" content="([^"]+)"/.exec(html)?.[1] ?? "";
    expect(description.length).toBeGreaterThan(80);
    expect(description).toContain("中央氣象署");
    expect(description).toContain("MCP");
  });

  it("declares canonical, keywords and the llms.txt describedby link", () => {
    expect(html).toMatch(/<link rel="canonical" href="https:\/\/[^"]+\/">/);
    expect(html).toMatch(/<meta name="keywords" content="[^"]{40,}">/);
    expect(html).toMatch(/<link rel="describedby" href="https:\/\/[^"]+\/llms\.txt" type="text\/markdown">/);
  });

  it("has the Open Graph and Twitter Card tags a link preview needs", () => {
    for (const property of ["og:type", "og:site_name", "og:locale", "og:url", "og:title", "og:description"]) {
      expect(html).toContain(`property="${property}"`);
    }
    for (const name of ["twitter:card", "twitter:title", "twitter:description"]) {
      expect(html).toContain(`name="${name}"`);
    }
  });

  it("uses twitter:card=summary, since there is deliberately no og:image", () => {
    // A summary_large_image card with no image renders as a broken/empty
    // banner. If someone adds an og:image later, this assertion is the
    // reminder to upgrade the card type at the same time.
    expect(html).toContain('name="twitter:card" content="summary"');
    expect(html).not.toMatch(/<meta[^>]+property="og:image"/);
  });

  it("carries valid schema.org JSON-LD describing the MCP service", () => {
    const raw = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/.exec(html)?.[1];
    expect(raw).toBeDefined();
    const parsed = JSON.parse(raw!);
    expect(parsed["@context"]).toBe("https://schema.org");
    const types = parsed["@graph"].map((node: { "@type": string }) => node["@type"]);
    expect(types).toContain("WebAPI");
    expect(types).toContain("SoftwareSourceCode");
    const api = parsed["@graph"].find((n: { "@type": string }) => n["@type"] === "WebAPI");
    expect(api.name).toBe("opendata-mcp");
    expect(api.isAccessibleForFree).toBe(true);
    expect(api.documentation).toContain("github.com");
  });

  it("uses semantic landmarks rather than only divs", () => {
    for (const tag of ["<main>", "</main>", "<header", "<nav", "<footer", "<h1", "<h2"]) {
      expect(html).toContain(tag);
    }
    // Exactly one h1 — multiple h1s muddy the page's primary topic.
    expect(html.match(/<h1\b/g)).toHaveLength(1);
  });

  it("renders the real headline stats in static HTML, not zeros that only JS fills in", () => {
    // The regression this guards: every counter used to ship as literal "0"
    // and animate up via JS, so a crawler (or any JS-off reader) saw a page
    // claiming 0 tools, 0 datasets and 0 tests.
    const stats = [...html.matchAll(/data-count-to="(\d+)"[^>]*>(\d+)</g)];
    expect(stats.length).toBeGreaterThanOrEqual(5);
    for (const [, target, rendered] of stats) {
      expect(rendered).toBe(target);
      expect(Number(rendered)).toBeGreaterThan(0);
    }
  });

  it("keeps the substantive copy in static HTML", () => {
    const text = html
      .replace(/<(script|style)[\s\S]*?<\/\1>/g, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim();
    expect(text.length).toBeGreaterThan(2000);
    expect(text).toContain("tw_weather_forecast");
    expect(text).toContain("政府資料開放授權條款");
  });
});

describe("GET /robots.txt", () => {
  it("serves plain text allowing general crawlers while excluding non-documents", async () => {
    const res = await worker.fetch(new Request(`${ORIGIN}/robots.txt`), env);
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toContain("text/plain");
    const body = await res.text();
    expect(body).toContain("User-agent: *");
    expect(body).toContain("Allow: /");
    expect(body).toContain("Disallow: /mcp");
    expect(body).toContain("Disallow: /health");
  });

  it("names every verified AI crawler with its own allow group", async () => {
    const body = await (await worker.fetch(new Request(`${ORIGIN}/robots.txt`), env)).text();
    for (const agent of AI_CRAWLER_USER_AGENTS) {
      expect(body).toContain(`User-agent: ${agent}`);
    }
    expect(AI_CRAWLER_USER_AGENTS).toContain("GPTBot");
    expect(AI_CRAWLER_USER_AGENTS).toContain("ClaudeBot");
    expect(AI_CRAWLER_USER_AGENTS).toContain("PerplexityBot");
  });

  it("points Sitemap at the requesting origin, so a self-hosted fork isn't sent here", () => {
    expect(buildRobotsTxt("https://my-fork.example.workers.dev")).toContain(
      "Sitemap: https://my-fork.example.workers.dev/sitemap.xml"
    );
  });
});

describe("GET /llms.txt", () => {
  it("serves markdown", async () => {
    const res = await worker.fetch(new Request(`${ORIGIN}/llms.txt`), env);
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toContain("text/markdown");
  });

  it("follows the llms.txt structure: H1, blockquote summary, then H2 link sections", async () => {
    const body = await (await worker.fetch(new Request(`${ORIGIN}/llms.txt`), env)).text();
    const lines = body.split("\n");
    expect(lines[0]).toBe("# opendata-mcp");
    // The spec's only two structural requirements: an H1 name, and a
    // blockquote short summary immediately establishing what this is.
    expect(lines.find(l => l.startsWith(">"))).toBeDefined();
    expect(body).toMatch(/^## 工具$/m);
    expect(body).toMatch(/^## 資料來源與授權$/m);
    // "Optional" has a defined meaning in the spec — links an agent may skip
    // when it needs a shorter context.
    expect(body).toMatch(/^## Optional$/m);
    // Link-list form: `- [Name](url): description`
    expect(body).toMatch(/^- \[[^\]]+\]\(https?:\/\/[^)]+\): .+$/m);
  });

  it("tells an agent how to get the authoritative tool list rather than trusting the summary", async () => {
    const body = await (await worker.fetch(new Request(`${ORIGIN}/llms.txt`), env)).text();
    expect(body).toContain("tools/list");
    expect(body).toContain(`${ORIGIN}/mcp`);
  });

  it("derives the dataset count from the registry so it cannot go stale", () => {
    const count = listDatasetEntries().length;
    expect(buildLlmsTxt(ORIGIN, count)).toContain(`目前登記 ${count} 筆資料集`);
    expect(count).toBeGreaterThan(0);
  });

  it("uses the requesting origin throughout", () => {
    const body = buildLlmsTxt("https://my-fork.example.workers.dev", 19);
    expect(body).toContain("https://my-fork.example.workers.dev/mcp");
    expect(body).not.toContain("dragonheartliu1440");
  });
});

describe("GET /sitemap.xml", () => {
  it("serves well-formed XML listing the indexable URLs", async () => {
    const res = await worker.fetch(new Request(`${ORIGIN}/sitemap.xml`), env);
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toContain("application/xml");
    const body = await res.text();
    expect(body.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true);
    expect(body).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');
    expect(body).toContain(`<loc>${ORIGIN}/</loc>`);
    expect(body).toContain(`<loc>${ORIGIN}/llms.txt</loc>`);
    // POST-only and liveness-only endpoints are not documents.
    expect(body).not.toContain(`<loc>${ORIGIN}/mcp</loc>`);
    expect(body).not.toContain(`<loc>${ORIGIN}/health</loc>`);
  });

  it("uses a fixed lastmod rather than today's date", () => {
    // Regenerating "now" on every request would claim daily changes that
    // never happened.
    const a = buildSitemapXml(ORIGIN, "2026-08-24");
    expect(a).toContain("<lastmod>2026-08-24</lastmod>");
  });
});

describe("per-request origin rewriting", () => {
  it("rewrites the canonical origin in the served HTML to the requesting origin", async () => {
    const res = await worker.fetch(new Request("https://my-fork.example.com/"), env);
    const body = await res.text();
    expect(body).toContain('<link rel="canonical" href="https://my-fork.example.com/">');
    expect(body).toContain('content="https://my-fork.example.com/"');
    expect(body).not.toContain("dragonheartliu1440");
  });

  it("rewrites the endpoint shown in the copy-to-clipboard script too", async () => {
    const res = await worker.fetch(new Request("https://my-fork.example.com/support.js"), env);
    const body = await res.text();
    expect(body).toContain("https://my-fork.example.com/mcp");
    expect(body).not.toContain("dragonheartliu1440");
  });

  it("leaves the canonical deployment's own bytes untouched", async () => {
    const res = await worker.fetch(
      new Request("https://opendata-mcp.dragonheartliu1440.workers.dev/"),
      env
    );
    expect(await res.text()).toBe(LANDING_PAGE_HTML);
  });
});
